export const INTERNAL_DOC_TYPE = "INTERNAL";
export const ORIGIN_EXTERNAL_DOC_TYPE = "ORIGIN_EXTERNAL";
export const DESTINATION_EXTERNAL_DOC_TYPE = "DESTINATION_EXTERNAL";

export const ROLE_USER = "ROLE_USER";
export const ROLE_ADMIN = "ROLE_ADMIN";