export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const GET_LOGGED_USER_DETAILS = "GET_LOGGED_USER_DETAILS";

export const GET_ERRORS = "GET_ERRORS";
export const GET_DOCUMENTS = "GET_DOCUMENTS";
