//security actions
export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";

//document actions
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_MY_DOCUMENTS_OPEN = "GET_MY_DOCUMENTS_OPEN";
export const GET_MY_DOCUMENTS_ARCHIVED = "GET_MY_DOCUMENTS_ARCHIVED";
export const GET_DOCUMENTS_RECEIVED_OPEN = "GET_DOCUMENTS_RECEIVED_OPEN";
export const GET_DOCUMENTS_RECEIVED_RESOLVED = "GET_DOCUMENTS_RECEIVED_RESOLVED";
export const GET_DOCUMENTS_RECEIVED_ARCHIVED = "GET_DOCUMENTS_RECEIVED_ARCHIVED";
export const SAVE_SEARCH_DETAILS = "SAVE_SEARCH_DETAILS";
export const DOCUMENT_CREATED = "DOCUMENT_CREATED";
export const DOCUMENT_RESENT = "DOCUMENT_RESENT";

//file actions
export const UPLOAD_FILE = "UPLOAD_FILE";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";

//user actions
export const GET_ALL_USERS = "GET_ALL_USERS";
export const UPDATE_SELECTED_USERS_FOR_DOCUMENT_HISTORY = "UPDATE_SELECTED_USERS_FOR_DOCUMENT_HISTORY";
export const UPDATE_SELECTED_USERS_FOR_ORIGIN_SEARCH = "UPDATE_SELECTED_USERS_FOR_ORIGIN_SEARCH";
export const UPDATE_SELECTED_USERS_FOR_DESTINATION_SEARCH = "UPDATE_SELECTED_USERS_FOR_DESTINATION_SEARCH";
export const UPDATE_ALL_USERS = "UPDATE_ALL_USERS";
export const GET_ALL_DEPARTMENTS = "GET_ALL_DEPARTMENTS";

//admin actions
export const GET_PENDING_USERS = "GET_PENDING_USERS";

//general actions
export const GET_ERRORS = "GET_ERRORS";